web/mysite/backend/exampleapp/urls.py
from django.urls import path

from . import views

app_name = 'exampleapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

web/mysite/backend/mysite/urls.py
from django.conf.urls import include, url  # noqa
from django.urls import path
from django.contrib import admin
from django.shortcuts import redirect

import django_js_reverse.views


urlpatterns = [
    path("", lambda request : redirect("/exampleapp/")),
    path("admin/", admin.site.urls, name="admin"),
    path("jsreverse/", django_js_reverse.views.urls_js, name="js_reverse"),
    path("exampleapp/", include("exampleapp.urls"), name="exampleapp"),
]

web/mysite/backend/common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from model_utils.fields import AutoCreatedField, AutoLastModifiedField


class IndexedTimeStampedModel(models.Model):
    created = AutoCreatedField(_("created"), db_index=True)
    modified = AutoLastModifiedField(_("modified"), db_index=True)

    class Meta:
        abstract = True

web/mysite/backend/exampleapp/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

web/mysite/backend/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import ugettext_lazy as _

from common.models import IndexedTimeStampedModel

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin, IndexedTimeStampedModel):
    email = models.EmailField(max_length=255, unique=True)
    is_staff = models.BooleanField(
        default=False, help_text=_("Designates whether the user can log into this admin " "site.")
    )
    is_active = models.BooleanField(
        default=True,
        help_text=_(
            "Designates whether this user should be treated as "
            "active. Unselect this instead of deleting accounts."
        ),
    )

    objects = UserManager()

    USERNAME_FIELD = "email"

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.email

web/mysite/backend/exampleapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'exampleapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'exampleapp/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'exampleapp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'exampleapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('exampleapp:results', args=(question.id,)))

web/mysite/backend/users/views.py
from django.shortcuts import render  # noqa


# Create your views here.

web/mysite/backend/templates/base.html
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="shortcut icon" href="#" />

  <!-- Webpack rendered CSS -->
  {% render_bundle 'main' 'css' %}
</head>

<body>
  {% include 'includes/sentry_init.html' %}

  <!-- Body Content -->
  {% block body %}{% endblock %}

  <!-- django-js-reverse -->
  <script src="{% url 'js_reverse' %}" type="text/javascript"></script>

  <!-- Webpack rendered Javascript -->
  {% render_bundle 'vendors~main' 'js' 'DEFAULT' %} {% render_bundle 'main' 'js' 'DEFAULT' %}
  {% block scripts %}{% endblock %}
</body>
</html>

web/mysite/backend/templates/exampleapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'exampleapp:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
  {% endfor %}
  <input type="submit" value="Vote">
</form>

web/mysite/backend/templates/exampleapp/index.html
{% extends 'base.html' %}


{% block body %}
  <h1>Django React Boilerplate Example App</h1>

  <p>The setup of the Django React Boilerplate Example App was successful.</p>

  <h2>React Example App</h2>
  <p>Here is an example of a React app included in the Django framework:</p>

  <div id="react-app"></div>

  <h2>Django Example App</h2>
  <p>This is an example Django app for creating, reading and voting on polls. The app closely follows the official
    Django tutorial available <a href="https://docs.djangoproject.com/en/2.2/intro/tutorial01/">here</a>.</p>

  <p>Questions and Choices can be created in the <a href="/admin/">Admin interface</a>. Please make sure that you have
    created a superuser with the command <code>'python manage.py createsuperuser'</code>.</p>

  <h3>Polls</h3>
  {% if latest_question_list %}
    <p>List of polls available:</p>
    <ul>
      {% for question in latest_question_list %}
        <li><a href="{% url 'exampleapp:detail' question.id %}">{{ question.question_text }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No polls are available.</p>
  {% endif %}
{% endblock %}

web/mysite/backend/templates/exampleapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'exampleapp:detail' question.id %}">Vote again?</a>

web/mysite/backend/templates/includes/sentry_init.html
<script>
    window.SENTRY_DSN = "{{ SENTRY_DSN }}";
    window.COMMIT_SHA = "{{ COMMIT_SHA }}";
</script>